Fix import bug for run_reports.sh . Remove unused imports.
Import bug:
  File "/opt/galaxy-central/lib/galaxy/webapps/reports/buildapp.py", line 25, in <module>
    class ReportsWebApplication( galaxy.web.framework.webapp.WebApplication ):
AttributeError: 'module' object has no attribute 'webapp'

The bug was introduced by commit d57655849ac4 .


Former-commit-id: 789625660000a10ea1ad549be48ee60e8cc67c56