Improved logic for determining if zipfile compression is implemented. Had the following spurious error occur in production.
Traceback (most recent call last):
  File "./scripts/extract_dataset_part.py", line 25, in <module>
    import galaxy.model.mapping #need to load this before we unpickle, in order to setup properties assigned by the mappers
  File "/opt/galaxy/web/lib/galaxy/model/__init__.py", line 13, in <module>
    import galaxy.datatypes.registry
  File "/opt/galaxy/web/lib/galaxy/datatypes/registry.py", line 5, in <module>
    import data, tabular, interval, images, sequence, qualityscore, genetics, xml, coverage, tracks, chrominfo, binary, assembly, ngsindex
  File "/opt/galaxy/web/lib/galaxy/datatypes/data.py", line 43, in <module>
    os.rmdir( tmpd )
OSError: [Errno 39] Directory not empty: '/mnt/galaxyData/tmp/516.1.all.q/tmpF25FKf'

Rework logic to check if zipfile compression is available without actually creating directories and files. This should eliminate this error and marginally improve Galaxy performance/robustness. Again looking through the Python source code as well as documentation, I believe this is equivalent to the old version.


Former-commit-id: 855e8ca2ccc3a6ab13bf4cfe2d206a3b57ec766b