Add exception handling for Binary sniffers. Image sniffers can fail for large files because signed integers are used internally, this catches that and other potential problems.
Traceback (most recent call last):
  File "/opt/galaxy/web/tools/data_source/upload.py", line 432, in <module>
    __main__()
  File "/opt/galaxy/web/tools/data_source/upload.py", line 421, in __main__
    add_file( dataset, registry, json_file, output_path )
  File "/opt/galaxy/web/tools/data_source/upload.py", line 155, in add_file
    type_info = Binary.is_sniffable_binary( dataset.path )
  File "/opt/galaxy/web/lib/galaxy/datatypes/binary.py", line 38, in is_sniffable_binary
    if format["class"]().sniff(filename):
  File "/opt/galaxy/web/lib/galaxy/datatypes/images.py", line 203, in sniff
    headers = get_headers(filename, None, 1)
  File "/opt/galaxy/web/lib/galaxy/datatypes/sniff.py", line 179, in get_headers
    for idx, line in enumerate(file(fname)):
SystemError: Negative size passed to PyString_FromStringAndSize

Former-commit-id: 5f227a4d2e4db876b67bab5e0356934659e37dd4